// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
// The Prisma CLI runs outside Next.js, so it doesn't auto-load .env.local.
// Load it explicitly (takes precedence), then fall back to .env.
config({ path: ".env.local" });
config();
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (non-pooled) connection. Fall back to
    // DATABASE_URL if DIRECT_URL isn't set (e.g. non-Neon Postgres).
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
